apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  ports:
    - port: 61616
      targetPort: 61616
    - port: 8161
      targetPort: 8161
  selector:
    app: fleetman-queue
  type: ClusterIP
